### ISSUE TITLE
Failed to load object

### ISSUE THREAD

**Issue by Richard-L** [danielmeinert/objectcreator#3]
On some objects, this error occurs:

https://github.com/danielmeinert/objectcreator/assets/4934209/8da2363d-fec6-4bb1-89b7-11bfa6fcd365

Source file: [REELEAGL.zip](https://github.com/danielmeinert/objectcreator/files/11645466/REELEAGL.zip)

**Comment by danielmeinert** [comment]
Thanks, I'll investigate.

**Comment by danielmeinert** [comment]
The object in question is a ride...

**Comment by Richard-L** [comment]
So the tool is very restricted to what it will open, or is intended to? I'm confused as to the restrictions.

**Comment by danielmeinert** [comment]
Because at the moment it can only handle small scenery as stated in the release note. Everything else will throw an error because there is no code how to deal with these object types (which, again, will eventually be added of course). But surely it won't ever be able to handle rides. 
I decided to release the 0.1 version with the smallest possible object type support (simple small scenery) to give people the opportunity to test the tool without needing to install the python develop version. I'm just not at the point of having other types done at this moment.

**Comment by danielmeinert** [comment]
For what it's worth, I improved the loading error message (to be released in the next version).

**Comment by Richard-L** [comment]
Yep was going to suggest instead of the "failed" it would be better to say "<type> is not supported".
