### ISSUE TITLE
Cannot close opened objects

### ISSUE THREAD

**Issue by Richard-L** [danielmeinert/objectcreator#4]
It currently doesn't seem possible to close opened objects. I presume this has to do with it saying "(locked)"? If so, it's unintuitive what this should mean.

https://github.com/danielmeinert/objectcreator/assets/4934209/9fd2bbf0-2d93-4208-a369-6accef04398d

EDIT: I see now opened files can only be closed from the right tabs. Why is this? I think you want to unify this behaviour.

**Comment by danielmeinert** [comment]
The reason is that eventually sprites and objects can be decoupled, i.e. 'unlocked'. So on the left you can have sprites open with no objects. But yeah, as long as both tabs are locked, clicking on the x for the sprite could induce an object closing. I hope the whole behaviour will become more intuitive once the full functionality is there.

**Comment by Richard-L** [comment]
That's interesting.

I still think it would help to bundle both under one and the same tab. If either content needs to be transferred from one item to the other there would ideally be a separate option for that imo.
